// Country name → ISO-3166 alpha-2 → Unicode flag emoji.
//
// FIVB/VIS country strings are standard English names, so we map by name. The table
// below is authored as ISO2 → [name variants] (easy to read/extend) and reversed into a
// normalized lookup at load time. Names are normalized (lowercased, diacritics stripped,
// punctuation removed) so "Côte d'Ivoire" / "Cote d'Ivoire" / "Ivory Coast" all resolve.

const COUNTRY_NAMES: Record<string, string[]> = {
  AF: ['Afghanistan'],
  AL: ['Albania'],
  DZ: ['Algeria'],
  AS: ['American Samoa'],
  AD: ['Andorra'],
  AO: ['Angola'],
  AG: ['Antigua and Barbuda'],
  AR: ['Argentina'],
  AM: ['Armenia'],
  AW: ['Aruba'],
  AU: ['Australia'],
  AT: ['Austria'],
  AZ: ['Azerbaijan'],
  BS: ['Bahamas', 'The Bahamas'],
  BH: ['Bahrain'],
  BD: ['Bangladesh'],
  BB: ['Barbados'],
  BY: ['Belarus'],
  BE: ['Belgium'],
  BZ: ['Belize'],
  BJ: ['Benin'],
  BM: ['Bermuda'],
  BT: ['Bhutan'],
  BO: ['Bolivia', 'Plurinational State of Bolivia'],
  BA: ['Bosnia and Herzegovina', 'Bosnia & Herzegovina', 'Bosnia'],
  BW: ['Botswana'],
  BR: ['Brazil'],
  BN: ['Brunei', 'Brunei Darussalam'],
  BG: ['Bulgaria'],
  BF: ['Burkina Faso'],
  BI: ['Burundi'],
  KH: ['Cambodia'],
  CM: ['Cameroon'],
  CA: ['Canada'],
  CV: ['Cape Verde', 'Cabo Verde'],
  KY: ['Cayman Islands'],
  CF: ['Central African Republic'],
  TD: ['Chad'],
  CL: ['Chile'],
  CN: ['China', "People's Republic of China"],
  CO: ['Colombia'],
  KM: ['Comoros'],
  CG: ['Congo', 'Republic of the Congo', 'Congo Brazzaville'],
  CD: ['DR Congo', 'Democratic Republic of the Congo', 'Congo DR', 'Congo Kinshasa'],
  CK: ['Cook Islands'],
  CR: ['Costa Rica'],
  CI: ['Ivory Coast', "Cote d'Ivoire", "Côte d'Ivoire"],
  HR: ['Croatia'],
  CU: ['Cuba'],
  CW: ['Curacao', 'Curaçao'],
  CY: ['Cyprus'],
  CZ: ['Czechia', 'Czech Republic'],
  DK: ['Denmark'],
  DJ: ['Djibouti'],
  DM: ['Dominica'],
  DO: ['Dominican Republic'],
  EC: ['Ecuador'],
  EG: ['Egypt'],
  SV: ['El Salvador'],
  GQ: ['Equatorial Guinea'],
  ER: ['Eritrea'],
  EE: ['Estonia'],
  SZ: ['Eswatini', 'Swaziland'],
  ET: ['Ethiopia'],
  FJ: ['Fiji'],
  FI: ['Finland'],
  FR: ['France'],
  PF: ['French Polynesia', 'Tahiti'],
  GA: ['Gabon'],
  GM: ['Gambia', 'The Gambia'],
  GE: ['Georgia'],
  DE: ['Germany'],
  GH: ['Ghana'],
  GB: ['Great Britain', 'United Kingdom', 'UK', 'England'],
  GR: ['Greece'],
  GD: ['Grenada'],
  GU: ['Guam'],
  GT: ['Guatemala'],
  GN: ['Guinea'],
  GW: ['Guinea-Bissau'],
  GY: ['Guyana'],
  HT: ['Haiti'],
  HN: ['Honduras'],
  HK: ['Hong Kong', 'Hong Kong China'],
  HU: ['Hungary'],
  IS: ['Iceland'],
  IN: ['India'],
  ID: ['Indonesia'],
  IR: ['Iran', 'Islamic Republic of Iran'],
  IQ: ['Iraq'],
  IE: ['Ireland'],
  IL: ['Israel'],
  IT: ['Italy'],
  JM: ['Jamaica'],
  JP: ['Japan'],
  JO: ['Jordan'],
  KZ: ['Kazakhstan'],
  KE: ['Kenya'],
  KI: ['Kiribati'],
  KP: ['North Korea', 'DPR Korea', 'Korea DPR', "Democratic People's Republic of Korea"],
  KR: ['Korea', 'South Korea', 'Republic of Korea', 'Korea Republic'],
  XK: ['Kosovo'],
  KW: ['Kuwait'],
  KG: ['Kyrgyzstan'],
  LA: ['Laos', "Lao People's Democratic Republic"],
  LV: ['Latvia'],
  LB: ['Lebanon'],
  LS: ['Lesotho'],
  LR: ['Liberia'],
  LY: ['Libya'],
  LI: ['Liechtenstein'],
  LT: ['Lithuania'],
  LU: ['Luxembourg'],
  MO: ['Macau', 'Macao'],
  MG: ['Madagascar'],
  MW: ['Malawi'],
  MY: ['Malaysia'],
  MV: ['Maldives'],
  ML: ['Mali'],
  MT: ['Malta'],
  MH: ['Marshall Islands'],
  MR: ['Mauritania'],
  MU: ['Mauritius'],
  MX: ['Mexico'],
  FM: ['Micronesia', 'Federated States of Micronesia'],
  MD: ['Moldova', 'Republic of Moldova'],
  MC: ['Monaco'],
  MN: ['Mongolia'],
  ME: ['Montenegro'],
  MA: ['Morocco'],
  MZ: ['Mozambique'],
  MM: ['Myanmar', 'Burma'],
  NA: ['Namibia'],
  NR: ['Nauru'],
  NP: ['Nepal'],
  NL: ['Netherlands', 'The Netherlands', 'Holland'],
  NC: ['New Caledonia'],
  NZ: ['New Zealand'],
  NI: ['Nicaragua'],
  NE: ['Niger'],
  NG: ['Nigeria'],
  MK: ['North Macedonia', 'Macedonia', 'FYR Macedonia'],
  NO: ['Norway'],
  OM: ['Oman'],
  PK: ['Pakistan'],
  PW: ['Palau'],
  PS: ['Palestine', 'State of Palestine'],
  PA: ['Panama'],
  PG: ['Papua New Guinea'],
  PY: ['Paraguay'],
  PE: ['Peru'],
  PH: ['Philippines'],
  PL: ['Poland'],
  PT: ['Portugal'],
  PR: ['Puerto Rico'],
  QA: ['Qatar'],
  RO: ['Romania'],
  RU: ['Russia', 'Russian Federation'],
  RW: ['Rwanda'],
  KN: ['Saint Kitts and Nevis', 'St Kitts and Nevis', 'St. Kitts and Nevis'],
  LC: ['Saint Lucia', 'St Lucia', 'St. Lucia'],
  VC: ['Saint Vincent and the Grenadines', 'St Vincent and the Grenadines', 'St. Vincent and the Grenadines'],
  WS: ['Samoa'],
  SM: ['San Marino'],
  ST: ['Sao Tome and Principe', 'São Tomé and Príncipe'],
  SA: ['Saudi Arabia'],
  SN: ['Senegal'],
  RS: ['Serbia'],
  SC: ['Seychelles'],
  SL: ['Sierra Leone'],
  SG: ['Singapore'],
  SK: ['Slovakia'],
  SI: ['Slovenia'],
  SB: ['Solomon Islands'],
  SO: ['Somalia'],
  ZA: ['South Africa'],
  SS: ['South Sudan'],
  ES: ['Spain'],
  LK: ['Sri Lanka'],
  SD: ['Sudan'],
  SR: ['Suriname'],
  SE: ['Sweden'],
  CH: ['Switzerland'],
  SY: ['Syria', 'Syrian Arab Republic'],
  TW: ['Chinese Taipei', 'Taiwan'],
  TJ: ['Tajikistan'],
  TZ: ['Tanzania', 'United Republic of Tanzania'],
  TH: ['Thailand'],
  TL: ['Timor-Leste', 'East Timor'],
  TG: ['Togo'],
  TO: ['Tonga'],
  TT: ['Trinidad and Tobago'],
  TN: ['Tunisia'],
  TR: ['Turkey', 'Türkiye', 'Turkiye'],
  TM: ['Turkmenistan'],
  TV: ['Tuvalu'],
  UG: ['Uganda'],
  UA: ['Ukraine'],
  AE: ['United Arab Emirates', 'UAE'],
  US: ['United States', 'United States of America', 'USA', 'America'],
  UY: ['Uruguay'],
  UZ: ['Uzbekistan'],
  VU: ['Vanuatu'],
  VE: ['Venezuela', 'Bolivarian Republic of Venezuela'],
  VN: ['Vietnam', 'Viet Nam'],
  VG: ['British Virgin Islands'],
  VI: ['US Virgin Islands', 'U.S. Virgin Islands'],
  YE: ['Yemen'],
  ZM: ['Zambia'],
  ZW: ['Zimbabwe'],
}

// Normalize a name for lookup: lowercase, strip diacritics + punctuation, collapse spaces.
function norm(s: string): string {
  return s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9 ]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

const NAME_TO_ISO2: Record<string, string> = {}
for (const [iso2, names] of Object.entries(COUNTRY_NAMES)) {
  for (const name of names) NAME_TO_ISO2[norm(name)] = iso2
}

// Two-letter ISO code → regional-indicator flag emoji.
function iso2ToFlag(iso2: string): string {
  return iso2
    .toUpperCase()
    .replace(/[^A-Z]/g, '')
    .replace(/./g, (ch) => String.fromCodePoint(0x1f1e6 + ch.charCodeAt(0) - 65))
}

// The flag emoji for a country name, or '' if unknown.
export function countryFlag(name?: string | null): string {
  if (!name) return ''
  const iso2 = NAME_TO_ISO2[norm(name)]
  return iso2 ? iso2ToFlag(iso2) : ''
}

// "🇫🇷 France" — name prefixed with its flag (just the name if unknown). For plain-text slots.
export function withFlag(name?: string | null): string {
  if (!name) return ''
  const flag = countryFlag(name)
  return flag ? `${flag} ${name}` : name
}
